feat: attach environment to initialization call
statsig-io/dart-sdk pull request #4
Opened 2022-08-04 14:19 UTC by savy-91

This is a starting point to address https://github.com/statsig-io/dart-sdk/issues/3

More specifically, at the moment this uses the environment when fetching experiments and other remote values, but it does not attach the environment to logged events.

2022-08-04 18:17 UTC, daniel-statsig commented on lib/src/statsig_options.dart
> +      "statSigEnvironment": <String, String>{"tier": environmentName}
The key for this is "statsigEnvironment"

2022-08-04 18:18 UTC, daniel-statsig commented on lib/src/statsig_options.dart
> +    switch (this) {
code golf: String environmentName = this.toString().replaceAll("StatsigEnvironment.", "");

2022-08-04 18:19 UTC, daniel-statsig requested changes
Awesome update! Thank you. The statsigEnvironment key needs to be updated though or this won't work.

2022-08-09 15:27 UTC, merged

2022-08-09 15:27 UTC, daniel-statsig commented
Thank you for this

2022-08-09 16:30 UTC, tore-statsig commented on lib/src/network_service.dart
> +                ..addAll(_options.environment?.toJson() ?? {}),
This is great for `initialize`, but now we arent setting environment on log events.  We need to make a copy of the user that comes in, add environment to it, so it gets sent with initialize and each event